### ISSUE TITLE
Correct german translation

### ISSUE THREAD

**Issue by derrapf** [ioBroker/ioBroker.rickshaw#4]
Please correct german translation in rickshaw adapter (0.4.5) as follows:

"Eingangs data"  to "Eingangs Daten"
"Legende und Axes" to "Legende und Achsen"
"Range:"              to "Bereich"
"Anzahl Werten:"  to "Anzahl Werte:"
"Höche:"               to "Höhe:"
"Charttyp:"            to "Chart Typ:"
"Zeige Axe unten:" to "Zeige Achse unten:"
"Zeige Axe links:"   to "Zeige Achse links:"
"Zeige Axe rechts:" to "Zeige Achse rechts:"
"Predefined background:"  to "Hintergrundfarbe"
"Hover details:"  to "Hover-Details"
"Smoothing"  to "Glätten"
"Preview:"     to "Vorschau"
"Nach Komma"  to "Nachkommastellen"
"B. Position:" to "Beschr. Position:"

Regards Ralf

**Comment by informaniac** [comment]
I added those (and other) corrections in PR #6
